### ISSUE TITLE
コンパイルってどうしてますか？

### ISSUE THREAD

**Issue by yfujii01** [keita-ito0221/test#2]
@shijratgah 
コンパイル方法が分かりませんでした。

Makefileを使用していると聞いたのですがあってますか？
EV3フォルダ内にMakefileが無く「Makefile.inc」があったのですが、これだけでmakeできるんでしょうか？

実際に行っている手順を教えてください:bow:

**Comment by shijratgah** [comment]
@yfujii01 
コンパイルの方法ですが
cygwinのgccを使ってコンパイルします。
cygwinのcdでコンパイルしたいディレクトリまで移動して
「make app=任意のディレクトリ名」
でコンパイルできます。

※スペースを空けるのはmakeとappの間だけです他は詰めて書いてください。

cygwinの設定は以下のサイトを見て構築しました。
以下URLです。
http://dev.toppers.jp/trac_user/ev3pf/wiki/DevEnv

以上です。お願いします。

**Comment by yfujii01** [comment]
@shijratgah 
「コンパイルしたいディレクトリ」とは「keita-ito0221/test」のことでしょうか？
それとも「keita-ito0221/test/EV3」のことでしょうか？

**Comment by shijratgah** [comment]
@yfujii01 
https://github.com/keita-ito0221/test
をクローンしてtest-masterの中にある「EV3」
をコンパイルしてもらう形になります。

「make app=test-master/EV3」もしくは、
「test-master$ make app=EV3」でコンパイルできます。

**Comment by yfujii01** [comment]
@shijratgah 
「test-master」ディレクトリの直下には何かファイルが存在するでしょうか？

私のディレクトリはEV3があるだけです。
```sh
$ ls
EV3/
$
```

そしてMakefileが無いのでこんなエラーが出ます。
```sh
$ make app=EV3
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by shijratgah** [comment]
すみません、勘違いしてました。
Makefileを会社の方のメールで送付します。

**Comment by yfujii01** [comment]
@shijratgah 
分かりました。
中身をちょっと見た感じ、コンパイルするだけでも他に準備が色々必要そうですね。
時間が取れたら確認してまた聞かせてもらうかもしれません:bow:

ちなみにMakefileはなんでgit管理されてないのでしょうか？
皆独自のMakefileを用意しているとか？

**Comment by shijratgah** [comment]
@yfujii01 
Makefileは皆同じのモノを使っています。

Makefileがgit管理されていないのは、見落としていたからです。
このことを新人で共有しようと思います。

**Comment by yfujii01** [comment]
@shijratgah 
コンパイルできました。

http://dev.toppers.jp/trac_user/ev3pf/wiki/DevEnv
↑提示してもらったここの説明をちゃんと読めてなかっただけでした。

Makefileもダウンロードしたものを使っていただけだったんですね。

hrp2/sdk/workspaceにgit cloneするということが分からず苦戦してしまいましたがなんとかなりました。
回答ありがとうございました。
